version = 0.1
[default.deploy.parameters]
stack_name = "sebastian-rone-serverless"
resolve_s3 = true
s3_prefix = "sebastian-rone-serverless"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
