AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.booleanuk.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 120
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  MySpringTodoApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/todos'

    Export:
      Name: MySpringTodoApi